### ISSUE TITLE
docker 无法启动 ，docker compose 如下

### ISSUE THREAD

**Issue by DC-Joney** [gozeon/yapii#13]
docker 无法直接启动，请问docker镜像如何制作，我看您制作的docker镜像还需要手动npm start，而且我手动npm start的时候海报错了，报错信息如下：
```
```
sh: nodemon: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! yapii@2.2.0 start: `nodemon server/app.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yapii@2.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2025-03-12T06_35_26_744Z-debug.log

docker-compose.yml 如下：

```
version: '3'
services:
  yapi:
    image: yapii:latest
    container_name: "yapii"
    restart: always
    ports:
      - 4000:4000


    deploy:
      resources:
        limits:
          memory: 1024m

    volumes:
      - ./app:/app:rw

    networks:
      - yapi_net

    depends_on:
      - mongo

  mongo:
    image: mongo:5 # 选择mongodb版本
    restart: always  # 自启动
    container_name: "mongo"
    ports:
      - 27017:27017 # 映射宿主机端口
    volumes:
      - ./mongodb/db:/data/db    # 挂载数据文件，根据实际路径修改 ：前的路径
      - ./mongodb/log:/var/log/mongodb  # 挂载日志文件，根据实际路径修改 ：前的路径
      - ./mongodb/config/mongod.conf:/etc/mongo/mongod.conf  # 挂载配置文件，根据实际路径修改 ：前的路径
      - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/ #设置容器启动脚本


    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=admin

    networks:
      - yapi_net

networks:
  yapi_net:
    driver: bridge
```
